Adição da explicação sobre lambda.
grupy-sanca/curso-python pull request #130
Opened 2022-10-31 21:43 UTC by anasampa

Oi. Adicionei conteúdo sobre lambda, que não achei no curso. Está simples, mas acho que passa uma ideia geral e pode ser complementado depois :).

2022-10-31 23:22 UTC, julianaklulo requested changes
Ficou bem bacana o conteúdo, obrigada pela contribuição!

O build falhou por estar faltando linha em branco após a definição dos blocos de doctest, fiz algumas sugestões com os blocos corrigidos.

2022-10-31 23:22 UTC, julianaklulo commented on source/lambda.rst
> +>>> lambda x,y,z: x+y+z
```suggestion
.. doctest::

   >>> lambda x,y,z: x+y+z
```

2022-10-31 23:22 UTC, julianaklulo commented on source/lambda.rst
> +10
```suggestion
.. doctest::

   >>> def duplica(x):
   ...   return 2*x
   >>> duplica(5)
   10
   >>> duplica = lambda x: 2*x
   >>> duplica(5)
   10
```

2022-10-31 23:22 UTC, julianaklulo commented on source/lambda.rst
> +'ODRAUDE'
```suggestion
.. doctest::

   >>> letra_maiuscula = lambda string: string[0].upper() + string[1:]
   >>> letra_maiuscula('maria')
   'Maria'
   >>> inverte = lambda string: string[::-1]
   >>> inverte('EDUARDO')
   'ODRAUDE'
```

2022-10-31 23:22 UTC, julianaklulo commented on source/lambda.rst
> +40
```suggestion
.. doctest::

   >>> def multiplica(n):
   ...   return lambda x: n*x
   >>> multiplica(3)
   <function __main__.multiplica.<locals>.<lambda>(x)>
   >>> triplica = multiplica(3)
   >>> triplica(10)
   30
   >>> quadruplica = multiplica(4)
   >>> quadruplica(10)
   40
```

2022-11-01 00:06 UTC, anasampa commented
Oi! Obrigada pelas sugestões.

2022-11-01 00:30 UTC, julianaklulo requested changes
Faltou ajeitar o comprimento dessa linha, acho que depois disso o build vai funcionar.

2022-11-01 00:30 UTC, julianaklulo commented on source/lambda.rst
> +--------------
```suggestion
Lambda e strings
----------------
```

2022-11-01 01:27 UTC, anasampa commented
Ajustado. Obrigada por ver os erros.

2022-11-01 01:52 UTC, julianaklulo approved these changes

2022-11-01 01:53 UTC, merged