Add exercises - 'PyBar' and 'Coding Dojo'
grupy-sanca/curso-python pull request #92
Opened 2020-10-25 11:55 UTC by anadulce

Add new exercises: PyBar and Coding Dojo

2020-10-25 17:55 UTC, heitorPB requested changes

2020-10-25 17:55 UTC, heitorPB commented on source/exercicios_listas.rst
> +      .. code-block:: python3
precisa de uma linha em branco depois de `.. code-block:: python3`

2020-10-25 17:55 UTC, heitorPB commented on source/exercicios_listas.rst
> +      .. code-block:: python3
precisa de uma linha em branco depois de `.. code-block:: python3`

2020-10-26 01:47 UTC, anadulce commented on source/exercicios_listas.rst
> +      .. code-block:: python3
Ok, vou acertar isso :)

2021-02-23 13:18 UTC, heitorPB requested changes

2021-02-23 13:18 UTC, heitorPB commented on source/exercicios_listas.rst
> +      .. code-block:: python3
```suggestion
      .. code-block:: python3
      
```

2021-02-23 13:18 UTC, heitorPB commented on source/exercicios_listas.rst
> +      .. code-block:: python3
```suggestion
      .. code-block:: python3
      
```

2021-02-23 13:28 UTC, heitorPB approved these changes

2021-02-23 13:56 UTC, heitorPB commented
merged in f61806e

2021-02-23 13:56 UTC, closed without merging