typos nas strings das listas lista1, lista2 e lista3
grupy-sanca/curso-python pull request #98
Opened 2020-10-27 20:18 UTC by marcelomiky

2020-10-27 20:28 UTC, heitorPB requested changes

2020-10-27 20:28 UTC, heitorPB commented on source/dicionarios.rst
> +     >>> lista3 = ["ovo frito", "ovo", "óleo", "condimentos a gosto"]
Essas listas devem ter dois elementos:
```python
>>> l1 = ['a', 'bla blabla']
>>> l2 = ['b', 'ble bleble']
>>> dict([l1, l2])
{'a': 'bla blabla', 'b': 'ble bleble'}
```
e não:
```python
>>> l3 = ['a', 'b', 'c']
>>> l4 = [1, 2, 3]
>>> dict([l3, l4])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: dictionary update sequence element #0 has length 3; 2 is required
>
```

2020-10-27 20:45 UTC, marcelomiky commented on source/dicionarios.rst
> +     >>> lista3 = ["ovo frito", "ovo", "óleo", "condimentos a gosto"]
Ahh, certo. Saquei!

2020-10-27 21:19 UTC, heitorPB commented
Você começou sua branch de uma "versão" antiga da master, poderia dar um rebase? A parte sobre unir dicts tá faltando um pedaço. É algo como:

```
git checkout master
git fetch upstream
git merge upstream/master
git checkout sua_branch
git rebase master #aqui pode dar treta
git push --force
```

2020-10-28 11:53 UTC, marcelomiky commented
O  que está faltando na união dos dicionários?

2021-01-15 18:19 UTC, heitorPB approved these changes

2021-01-15 18:19 UTC, merged